### ISSUE TITLE
Can't find the "@prefix@/share/@PACKAGE_NAME@/@DTD@"

### ISSUE THREAD

**Issue by cTaoLee** [primait/docker-tsung#2]
using by **docker run -v F:\project\tsung\tsung.xml:/root/.tsung/tsung.xml -v F:\project\tsung\logs\:/root/.tsung/log  -P prima/tsung start**
```Starting Tsung
Starting Tsung
Log directory is: /root/.tsung/log/20190313-0538
Config Error, aborting ! dtd_not_found
```

**Comment by TuxBoy** [comment]
@cTaoLee You can recover the file on your local http://tsung.erlang-projects.org/user_manual/dtd.html then you add the mapping volume in your docker:
```
docker run -v F:\project\tsung\tsung.xml:/root/.tsung/tsung.xml -v F:\project\tsung\logs:/root/.tsung/log -v /path/your/tsung-1.0.dtd:/usr/share/tsung/tsung-1.0.dtd -P prima/tsung start
```

**Comment by abhih** [comment]
The suggestion given by @TuxBoy  works so we can close this issue.
